export const API_PATH = {
  main: "/main-info",
  routine: "/routines",
  getCoachAll: "/coaches-all",
  mypage: "/users/me",
  editMyProfile: "/users/me",
  editMyCoachProfile: "/users/coaches",
  coachMypage: "/coaches",
  login: "/auth/login",
  logout: "/auth/logout",
  checkPassword: "/auth/confirm-password",
  checkEmail: "/auth/check-email",
  checkNickname: "/auth/check-nickname",
  reissue: "/auth/reissue",
  signup: "/auth/signup",
  withdraw: "/users/me",
  myCoaches: "/users/matched/coaches",
  notification: "/notifications",
  matchMembers: "/coaches/members",
  matchMember: "/coaches/member",
  patchMember: "/coaches/matched/members",
  auth: "/auth"
};
