export const API_PATH = {
  main: "/main-info",
  routine: "/routines",
  userProfile: "routines/user",
  category: "/categories",
  action: "/actions",
  getCoachAll: "/coaches-all",
  mypage: "/users/me",
  editMyProfile: "/users/me",
  editMyCoachProfile: "/coaches",
  coachMypage: "/coaches",
  login: "/auth/login",
  logout: "/auth/logout",
  checkPassword: "/auth/confirm-password",
  checkEmail: "/auth/check-email",
  checkNickname: "/auth/check-nickname",
  reissue: "/auth/reissue",
  signup: "/auth/signup",
  withdraw: "/users/me",
  myCoaches: "/users/matches",
  notification: "/notifications",
  match: "/coaches/matches",
  auth: "/auth"
};
